---
title: "Functions related to enrichment"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Functions related to enrichment}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE,
  fig.height = 4,
  fig.width = 10
)
```

```{r setup}
library(misctoolsr)
library(magrittr)
library(ggplot2)
```


```{r}
se <- exampleSE()
sigs <- exampleSignatures()
```


Create a contingency table

```{r}
contabs <- contingencyTable(x = se, cols = c("up", "down"), signatures = sigs)
contabs %>% 
    knitr::kable()
```

Perform Fisher's enrichment test on the contingency tables

```{r}
enrich_results <- enrichmentTestFisher(contabs = contabs)
enrich_results %>% 
    knitr::kable()
```

Plot results:

```{r}
plotFisherRes(enrich_results)
```

Perform Fisher's enrichment directly on a SummarizedExperiment

```{r}
ora_results <- ora(x = se, cols = c("up", "down"), signatures = sigs, alpha = 0.05)
ora_results %>% 
    knitr::kable()
```

Plot results:

```{r}
plotFisherRes(ora_results)
```

```{r}
p1 <- plotFisherRes(enrich_results)

```

